// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Mezc1LYYYLXmG6YOJDOF4WKSujDt-3M',
    appId: '1:209792077701:web:30fabd55873f6f65c7beec',
    messagingSenderId: '209792077701',
    projectId: 'second-chat-5eef5',
    authDomain: 'second-chat-5eef5.firebaseapp.com',
    storageBucket: 'second-chat-5eef5.firebasestorage.app',
    measurementId: 'G-2D314V92E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqT1qiRlpbqoucgnjJNoP5fZlyBVt-xc',
    appId: '1:209792077701:android:5777315ad86b58f7c7beec',
    messagingSenderId: '209792077701',
    projectId: 'second-chat-5eef5',
    storageBucket: 'second-chat-5eef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrOput8WUYRsFQvyXcm0SAXOmOmtkPr8',
    appId: '1:209792077701:ios:7eb0ffc390f2458cc7beec',
    messagingSenderId: '209792077701',
    projectId: 'second-chat-5eef5',
    storageBucket: 'second-chat-5eef5.firebasestorage.app',
    iosBundleId: 'com.secondChat.app',
  );
}